// Day #1 - 03_11_2022...
// After the SOLANA Workshop, Fall in Love with Rust...
// Thanks to Ayush Sir & Irffan...

// Basic Function(fn) to Print...
// Save the file with (.rs) extension...
fn main()
{
    println!("Hello Saksham!!");
}

// I'm using Atom Editor & script packages to run script...
// For Cli, open in path [>>> rustc hello.rs]...
// For Cli, ./hello...

// For Prompt, open in path [>>> rustc hello.rs]...
// For Prompt, [hello.exe]...

/*
Example of Multiline Comments...
Thank You ...
Rust :) ...
*/
