// Day #1 - 03_11_2022...

fn main() {
    // Define Variable using Keywork -> let ...
    // But this Variable is immutable...
    let x = 30; // i32 datatype...
    println!("The Value of Variable {} is {}.",'x',x);

    // To change manually datatype...
    let x: i64 = 30; // i64 datatype...
    // Now, u can store larger number in Variable x ...

    // For mutable Variable use Keywork -> mut...

    let mut z = 80;
    println!("The Old Value of Variable {} is {}.", 'z', z);

    z = 100;
    println!("The New Value of Variable {} is {}.",'z',z);

    // Use unsigned datatype to take only positive values...
    let y: u32 = 74; // u32 <- unsigned datatype...
    let f: f64 = 9.5; // f64 <- floating datatype...
    let b: bool = false; // boolean datatype...
}
