// Day #1 - 03_11_2022...
// First create application using Cargo...
// Excute [>>> cargo new <application_name> --bin]...
// '--bin' defines that created cargo is application not package...

// Basic Function(fn) to Print...
fn main() {
    println!("Hello, Cargo Run Test !");
}

// change the path [>>> cd <application_name>] ...
// Excute [>>> cargo run], to run application...